export const data_200EMA = [
  [
    { name: "Financial Services", value: 69.4 },
    { name: "Telecommunication", value: 61.9 },
    { name: "Information Technology", value: 61.8 },
    { name: "Healthcare", value: 68.5 },
    { name: "Forest Materials", value: 41.9 },
    { name: "Consumer Services", value: 64.0 },
    { name: "Diversified", value: 57.1 },
    { name: "FMCG", value: 42.3 },
    { name: "Metals & Mining", value: 65.1 },
    { name: "Construction", value: 75.9 },
    { name: "Power", value: 83.8 },
    { name: "Chemicals", value: 36.4 },
    { name: "Consumer", value: 38.0 },
    { name: "Capital Goods", value: 63.4 },
    // { name: "Utilities", value: 75.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 81.6 },
    { name: "Construction Materials", value: 47.9 },
    { name: "Commercial Services", value: 50.0 },
    { name: "Realty", value: 78.5 },
    { name: "Textiles", value: 46.3 },
    { name: "Media & Entertainment", value: 59.6 },
    { name: "Auto", value: 68.3 },
  ],
  [
    { name: "Financial Services", value: 68.4 },
    { name: "Telecommunication", value: 66.7 },
    { name: "Information Technology", value: 58.5 },
    { name: "Healthcare", value: 67.7 },
    { name: "Forest Materials", value: 32.3 },
    { name: "Consumer Services", value: 60.0 },
    { name: "Diversified", value: 50.0 },
    { name: "FMCG", value: 38.7 },
    { name: "Metals & Mining", value: 64.2 },
    { name: "Construction", value: 77.2 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 31.5 },
    { name: "Consumer", value: 35.2 },
    { name: "Capital Goods", value: 60.2 },
    // { name: "Utilities", value: 75.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 81.6 },
    { name: "Construction Materials", value: 47.9 },
    { name: "Commercial Services", value: 47.7 },
    { name: "Realty", value: 78.5 },
    { name: "Textiles", value: 43.3 },
    { name: "Media & Entertainment", value: 54.4 },
    { name: "Auto", value: 65.3 },
  ],
  [
    { name: "Financial Services", value: 67.5 },
    { name: "Telecommunication", value: 61.9 },
    { name: "Information Technology", value: 56.9 },
    { name: "Healthcare", value: 67.7 },
    { name: "Forest Materials", value: 29.0 },
    { name: "Consumer Services", value: 61.3 },
    { name: "Diversified", value: 50.0 },
    { name: "FMCG", value: 39.4 },
    { name: "Metals & Mining", value: 66.1 },
    { name: "Construction", value: 77.2 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 31.5 },
    { name: "Consumer", value: 35.2 },
    { name: "Capital Goods", value: 58.1 },
    // { name: "Utilities", value: 75.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 81.6 },
    { name: "Construction Materials", value: 45.2 },
    { name: "Commercial Services", value: 52.3 },
    { name: "Realty", value: 80.0 },
    { name: "Textiles", value: 43.3 },
    { name: "Media & Entertainment", value: 56.1 },
    { name: "Auto", value: 65.3 },
  ],
  [
    { name: "Financial Services", value: 71.8 },
    { name: "Telecommunication", value: 66.7 },
    { name: "Information Technology", value: 62.6 },
    { name: "Healthcare", value: 68.5 },
    { name: "Forest Materials", value: 38.7 },
    { name: "Consumer Services", value: 64.0 },
    { name: "Diversified", value: 57.1 },
    { name: "FMCG", value: 43.8 },
    { name: "Metals & Mining", value: 69.7 },
    { name: "Construction", value: 78.5 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 32.7 },
    { name: "Consumer", value: 39.4 },
    { name: "Capital Goods", value: 61.8 },
    // { name: "Utilities", value: 75.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 84.2 },
    { name: "Construction Materials", value: 47.9 },
    { name: "Commercial Services", value: 50.0 },
    { name: "Realty", value: 80.0 },
    { name: "Textiles", value: 44.0 },
    { name: "Media & Entertainment", value: 57.9 },
    { name: "Auto", value: 66.3 },
  ],
  [
    { name: "Financial Services", value: 72.2 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 62.6 },
    { name: "Healthcare", value: 68.5 },
    { name: "Forest Materials", value: 35.5 },
    { name: "Consumer Services", value: 65.3 },
    { name: "Diversified", value: 71.4 },
    { name: "FMCG", value: 43.8 },
    { name: "Metals & Mining", value: 69.7 },
    { name: "Construction", value: 79.7 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 35.2 },
    { name: "Consumer", value: 39.4 },
    { name: "Capital Goods", value: 64.4 },
    // { name: "Utilities", value: 75.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 84.2 },
    { name: "Construction Materials", value: 49.3 },
    { name: "Commercial Services", value: 59.1 },
    { name: "Realty", value: 78.5 },
    { name: "Textiles", value: 47.8 },
    { name: "Media & Entertainment", value: 57.9 },
    { name: "Auto", value: 68.3 },
  ],
  [
    { name: "Financial Services", value: 70.3 },
    { name: "Telecommunication", value: 66.7 },
    { name: "Information Technology", value: 61.8 },
    { name: "Healthcare", value: 68.5 },
    { name: "Forest Materials", value: 32.3 },
    { name: "Consumer Services", value: 60.0 },
    { name: "Diversified", value: 64.3 },
    { name: "FMCG", value: 40.1 },
    { name: "Metals & Mining", value: 68.8 },
    { name: "Construction", value: 81.0 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 34.0 },
    { name: "Consumer", value: 38.0 },
    { name: "Capital Goods", value: 61.3 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 78.9 },
    { name: "Construction Materials", value: 43.8 },
    { name: "Commercial Services", value: 52.3 },
    { name: "Realty", value: 78.5 },
    { name: "Textiles", value: 41.8 },
    { name: "Media & Entertainment", value: 56.1 },
    { name: "Auto", value: 68.3 },
  ],
  [
    { name: "Financial Services", value: 70.3 },
    { name: "Telecommunication", value: 66.7 },
    { name: "Information Technology", value: 58.5 },
    { name: "Healthcare", value: 66.1 },
    { name: "Forest Materials", value: 32.3 },
    { name: "Consumer Services", value: 61.3 },
    { name: "Diversified", value: 57.1 },
    { name: "FMCG", value: 38.0 },
    { name: "Metals & Mining", value: 67.0 },
    { name: "Construction", value: 79.7 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 30.9 },
    { name: "Consumer", value: 33.8 },
    { name: "Capital Goods", value: 60.2 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 78.9 },
    { name: "Construction Materials", value: 46.6 },
    { name: "Commercial Services", value: 54.5 },
    { name: "Realty", value: 78.5 },
    { name: "Textiles", value: 41.0 },
    { name: "Media & Entertainment", value: 54.4 },
    { name: "Auto", value: 66.3 },
  ],
  [
    { name: "Financial Services", value: 69.9 },
    { name: "Telecommunication", value: 66.7 },
    { name: "Information Technology", value: 56.1 },
    { name: "Healthcare", value: 66.9 },
    { name: "Forest Materials", value: 32.3 },
    { name: "Consumer Services", value: 61.3 },
    { name: "Diversified", value: 57.1 },
    { name: "FMCG", value: 37.2 },
    { name: "Metals & Mining", value: 67.9 },
    { name: "Construction", value: 78.5 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 29.0 },
    { name: "Consumer", value: 35.2 },
    { name: "Capital Goods", value: 61.8 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 78.9 },
    { name: "Construction Materials", value: 42.5 },
    { name: "Commercial Services", value: 54.5 },
    { name: "Realty", value: 76.9 },
    { name: "Textiles", value: 42.5 },
    { name: "Media & Entertainment", value: 56.1 },
    { name: "Auto", value: 68.3 },
  ],
  [
    { name: "Financial Services", value: 77.5 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 66.7 },
    { name: "Healthcare", value: 72.6 },
    { name: "Forest Materials", value: 38.7 },
    { name: "Consumer Services", value: 68.0 },
    { name: "Diversified", value: 64.3 },
    { name: "FMCG", value: 46.0 },
    { name: "Metals & Mining", value: 72.5 },
    { name: "Construction", value: 82.3 },
    { name: "Power", value: 89.2 },
    { name: "Chemicals", value: 42.6 },
    { name: "Consumer", value: 43.7 },
    { name: "Capital Goods", value: 68.1 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 84.2 },
    { name: "Construction Materials", value: 53.4 },
    { name: "Commercial Services", value: 59.1 },
    { name: "Realty", value: 83.1 },
    { name: "Textiles", value: 53.0 },
    { name: "Media & Entertainment", value: 66.7 },
    { name: "Auto", value: 72.3 },
  ],
  [
    { name: "Financial Services", value: 78.0 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 69.9 },
    { name: "Healthcare", value: 73.4 },
    { name: "Forest Materials", value: 45.2 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 64.3 },
    { name: "FMCG", value: 51.1 },
    { name: "Metals & Mining", value: 78.0 },
    { name: "Construction", value: 83.5 },
    { name: "Power", value: 89.2 },
    { name: "Chemicals", value: 48.1 },
    { name: "Consumer", value: 47.9 },
    { name: "Capital Goods", value: 73.3 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 89.5 },
    { name: "Construction Materials", value: 54.8 },
    { name: "Commercial Services", value: 65.9 },
    { name: "Realty", value: 83.1 },
    { name: "Textiles", value: 57.5 },
    { name: "Media & Entertainment", value: 64.9 },
    { name: "Auto", value: 74.3 },
  ],
  [
    { name: "Financial Services", value: 81.8 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 75.6 },
    { name: "Healthcare", value: 76.6 },
    { name: "Forest Materials", value: 48.4 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 64.3 },
    { name: "FMCG", value: 53.3 },
    { name: "Metals & Mining", value: 86.2 },
    { name: "Construction", value: 84.8 },
    { name: "Power", value: 91.9 },
    { name: "Chemicals", value: 54.3 },
    { name: "Consumer", value: 52.1 },
    { name: "Capital Goods", value: 77.0 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 89.5 },
    { name: "Construction Materials", value: 58.9 },
    { name: "Commercial Services", value: 65.9 },
    { name: "Realty", value: 86.2 },
    { name: "Textiles", value: 61.2 },
    { name: "Media & Entertainment", value: 73.7 },
    { name: "Auto", value: 74.3 },
  ],
  [
    { name: "Financial Services", value: 83.7 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 77.2 },
    { name: "Healthcare", value: 77.4 },
    { name: "Forest Materials", value: 51.6 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 71.4 },
    { name: "FMCG", value: 55.5 },
    { name: "Metals & Mining", value: 85.3 },
    { name: "Construction", value: 87.3 },
    { name: "Power", value: 91.9 },
    { name: "Chemicals", value: 57.4 },
    { name: "Consumer", value: 54.9 },
    { name: "Capital Goods", value: 78.0 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 86.8 },
    { name: "Construction Materials", value: 58.9 },
    { name: "Commercial Services", value: 63.6 },
    { name: "Realty", value: 89.2 },
    { name: "Textiles", value: 62.7 },
    { name: "Media & Entertainment", value: 73.7 },
    { name: "Auto", value: 75.2 },
  ],
  [
    { name: "Financial Services", value: 83.7 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 78.0 },
    { name: "Healthcare", value: 83.9 },
    { name: "Forest Materials", value: 48.4 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 78.6 },
    { name: "FMCG", value: 56.9 },
    { name: "Metals & Mining", value: 87.2 },
    { name: "Construction", value: 91.1 },
    { name: "Power", value: 91.9 },
    { name: "Chemicals", value: 61.7 },
    { name: "Consumer", value: 56.3 },
    { name: "Capital Goods", value: 79.1 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 89.5 },
    { name: "Construction Materials", value: 60.3 },
    { name: "Commercial Services", value: 65.9 },
    { name: "Realty", value: 92.3 },
    { name: "Textiles", value: 63.4 },
    { name: "Media & Entertainment", value: 77.2 },
    { name: "Auto", value: 75.2 },
  ],
  [
    { name: "Financial Services", value: 84.7 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 77.2 },
    { name: "Healthcare", value: 81.5 },
    { name: "Forest Materials", value: 54.8 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 78.6 },
    { name: "FMCG", value: 54.7 },
    { name: "Metals & Mining", value: 86.2 },
    { name: "Construction", value: 92.4 },
    { name: "Power", value: 91.9 },
    { name: "Chemicals", value: 57.4 },
    { name: "Consumer", value: 56.3 },
    { name: "Capital Goods", value: 79.1 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 92.1 },
    { name: "Construction Materials", value: 63.0 },
    { name: "Commercial Services", value: 68.2 },
    { name: "Realty", value: 92.3 },
    { name: "Textiles", value: 61.9 },
    { name: "Media & Entertainment", value: 71.9 },
    { name: "Auto", value: 75.2 },
  ],
  [
    { name: "Financial Services", value: 83.3 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 77.2 },
    { name: "Healthcare", value: 79.8 },
    { name: "Forest Materials", value: 48.4 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 78.6 },
    { name: "FMCG", value: 55.5 },
    { name: "Metals & Mining", value: 87.2 },
    { name: "Construction", value: 89.9 },
    { name: "Power", value: 91.9 },
    { name: "Chemicals", value: 58.0 },
    { name: "Consumer", value: 54.9 },
    { name: "Capital Goods", value: 77.0 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 89.5 },
    { name: "Construction Materials", value: 58.9 },
    { name: "Commercial Services", value: 63.6 },
    { name: "Realty", value: 92.3 },
    { name: "Textiles", value: 61.9 },
    { name: "Media & Entertainment", value: 64.9 },
    { name: "Auto", value: 76.2 },
  ],
  [
    { name: "Financial Services", value: 83.7 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 77.2 },
    { name: "Healthcare", value: 80.6 },
    { name: "Forest Materials", value: 48.4 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 78.6 },
    { name: "FMCG", value: 54.7 },
    { name: "Metals & Mining", value: 86.2 },
    { name: "Construction", value: 89.9 },
    { name: "Power", value: 91.9 },
    { name: "Chemicals", value: 61.7 },
    { name: "Consumer", value: 53.5 },
    { name: "Capital Goods", value: 77.5 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 92.1 },
    { name: "Construction Materials", value: 58.9 },
    { name: "Commercial Services", value: 61.4 },
    { name: "Realty", value: 92.3 },
    { name: "Textiles", value: 64.2 },
    { name: "Media & Entertainment", value: 68.4 },
    { name: "Auto", value: 75.2 },
  ],
  [
    { name: "Financial Services", value: 83.3 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 74.0 },
    { name: "Healthcare", value: 79.8 },
    { name: "Forest Materials", value: 45.2 },
    { name: "Consumer Services", value: 69.3 },
    { name: "Diversified", value: 71.4 },
    { name: "FMCG", value: 51.8 },
    { name: "Metals & Mining", value: 85.3 },
    { name: "Construction", value: 84.8 },
    { name: "Power", value: 89.2 },
    { name: "Chemicals", value: 60.5 },
    { name: "Consumer", value: 54.9 },
    { name: "Capital Goods", value: 77.0 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 92.1 },
    { name: "Construction Materials", value: 58.9 },
    { name: "Commercial Services", value: 68.2 },
    { name: "Realty", value: 87.7 },
    { name: "Textiles", value: 62.7 },
    { name: "Media & Entertainment", value: 64.9 },
    { name: "Auto", value: 76.2 },
  ],
  [
    { name: "Financial Services", value: 80.4 },
    { name: "Telecommunication", value: 66.7 },
    { name: "Information Technology", value: 62.6 },
    { name: "Healthcare", value: 77.4 },
    { name: "Forest Materials", value: 41.9 },
    { name: "Consumer Services", value: 65.3 },
    { name: "Diversified", value: 64.3 },
    { name: "FMCG", value: 46.7 },
    { name: "Metals & Mining", value: 80.7 },
    { name: "Construction", value: 83.5 },
    { name: "Power", value: 89.2 },
    { name: "Chemicals", value: 53.1 },
    { name: "Consumer", value: 50.7 },
    { name: "Capital Goods", value: 70.7 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 92.1 },
    { name: "Construction Materials", value: 53.4 },
    { name: "Commercial Services", value: 63.6 },
    { name: "Realty", value: 87.7 },
    { name: "Textiles", value: 55.2 },
    { name: "Media & Entertainment", value: 54.4 },
    { name: "Auto", value: 69.3 },
  ],
  [
    { name: "Financial Services", value: 79.9 },
    { name: "Telecommunication", value: 71.4 },
    { name: "Information Technology", value: 64.2 },
    { name: "Healthcare", value: 77.4 },
    { name: "Forest Materials", value: 38.7 },
    { name: "Consumer Services", value: 65.3 },
    { name: "Diversified", value: 78.6 },
    { name: "FMCG", value: 48.9 },
    { name: "Metals & Mining", value: 80.7 },
    { name: "Construction", value: 83.5 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 57.4 },
    { name: "Consumer", value: 49.3 },
    { name: "Capital Goods", value: 71.7 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 92.1 },
    { name: "Construction Materials", value: 50.7 },
    { name: "Commercial Services", value: 65.9 },
    { name: "Realty", value: 89.2 },
    { name: "Textiles", value: 56.0 },
    { name: "Media & Entertainment", value: 61.4 },
    { name: "Auto", value: 71.3 },
  ],
  [
    { name: "Financial Services", value: 77.0 },
    { name: "Telecommunication", value: 76.2 },
    { name: "Information Technology", value: 65.9 },
    { name: "Healthcare", value: 78.2 },
    { name: "Forest Materials", value: 38.7 },
    { name: "Consumer Services", value: 65.3 },
    { name: "Diversified", value: 71.4 },
    { name: "FMCG", value: 50.4 },
    { name: "Metals & Mining", value: 80.7 },
    { name: "Construction", value: 83.5 },
    { name: "Power", value: 86.5 },
    { name: "Chemicals", value: 56.2 },
    { name: "Consumer", value: 52.1 },
    { name: "Capital Goods", value: 71.7 },
    // { name: "Utilities", value: 100.0 },
    { name: "Oil, Gas & Consumable Fuels", value: 92.1 },
    { name: "Construction Materials", value: 54.8 },
    { name: "Commercial Services", value: 65.9 },
    { name: "Realty", value: 89.2 },
    { name: "Textiles", value: 56.0 },
    { name: "Media & Entertainment", value: 57.9 },
    { name: "Auto", value: 74.3 },
  ],
];
