export const data_50EMA = [
  [
    { name: "Realty", value: 11.8 },
    { name: "Utilities", value: 25 },
    { name: "Media Entertainment & Publication", value: 3.5 },
    { name: "Capital Goods", value: 20 },
    { name: "FMCG", value: 14.7 },
    { name: "Forest Materials", value: 6.2 },
    { name: "Information Technology", value: 15 },
    { name: "Diversified", value: 13.3 },
    { name: "Services", value: 10.9 },
    { name: "Healthcare", value: 17.6 },
    { name: "Power", value: 16.2 },
    { name: "Auto", value: 17.3 },
    { name: "Textiles", value: 11.8 },
    { name: "Chemicals", value: 11.8 },
    { name: "Metals & Mining", value: 15.5 },
    { name: "Construction Materials", value: 9.5 },
    { name: "Consumer Durables", value: 9.1 },
    { name: "Oil, Gas & Consumable fuels", value: 7.3 },
    { name: "Financial Services", value: 10 },
    { name: "Construction ", value: 12.2 },
    { name: "Consumer Services", value: 18.5 },
    { name: "Telecommunication", value: 13.6 },
  ],
  [
    { name: "Realty", value: 8.8 },
    { name: "Utilities", value: 0 },
    { name: "Media Entertainment & Publication", value: 5.3 },
    { name: "Capital Goods", value: 15.5 },
    { name: "FMCG", value: 10.5 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Information Technology", value: 11 },
    { name: "Diversified", value: 6.7 },
    { name: "Services", value: 8.7 },
    { name: "Healthcare", value: 9.9 },
    { name: "Power", value: 8.1 },
    { name: "Auto", value: 13.5 },
    { name: "Textiles", value: 11.8 },
    { name: "Chemicals", value: 11.2 },
    { name: "Metals & Mining", value: 15.5 },
    { name: "Construction Materials", value: 6.8 },
    { name: "Consumer Durables", value: 10.4 },
    { name: "Oil, Gas & Consumable fuels", value: 7.3 },
    { name: "Financial Services", value: 10.4 },
    { name: "Construction ", value: 9.8 },
    { name: "Consumer Services", value: 16 },
    { name: "Telecommunication", value: 9.1 },
  ],
  [
    { name: "Realty", value: 10.3 },
    { name: "Utilities", value: 0 },
    { name: "Media Entertainment & Publication", value: 7 },
    { name: "Capital Goods", value: 20 },
    { name: "FMCG", value: 13.3 },
    { name: "Forest Materials", value: 6.2 },
    { name: "Information Technology", value: 11 },
    { name: "Diversified", value: 6.7 },
    { name: "Services", value: 13 },
    { name: "Healthcare", value: 12.2 },
    { name: "Power", value: 10.8 },
    { name: "Auto", value: 14.4 },
    { name: "Textiles", value: 11.8 },
    { name: "Chemicals", value: 9.4 },
    { name: "Metals & Mining", value: 8.6 },
    { name: "Construction Materials", value: 5.4 },
    { name: "Consumer Durables", value: 9.1 },
    { name: "Oil, Gas & Consumable fuels", value: 4.9 },
    { name: "Financial Services", value: 10.4 },
    { name: "Construction ", value: 13.4 },
    { name: "Consumer Services", value: 18.5 },
    { name: "Telecommunication", value: 9.1 },
  ],
  [
    { name: "Realty", value: 19.1 },
    { name: "Utilities", value: 25 },
    { name: "Media Entertainment & Publication", value: 12.3 },
    { name: "Capital Goods", value: 30.5 },
    { name: "FMCG", value: 17.5 },
    { name: "Forest Materials", value: 18.8 },
    { name: "Information Technology", value: 16.5 },
    { name: "Diversified", value: 13.3 },
    { name: "Services", value: 17.4 },
    { name: "Healthcare", value: 19.1 },
    { name: "Power", value: 24.3 },
    { name: "Auto", value: 27.9 },
    { name: "Textiles", value: 19.1 },
    { name: "Chemicals", value: 11.8 },
    { name: "Metals & Mining", value: 23.3 },
    { name: "Construction Materials", value: 8.1 },
    { name: "Consumer Durables", value: 15.6 },
    { name: "Oil, Gas & Consumable fuels", value: 14.6 },
    { name: "Financial Services", value: 18.1 },
    { name: "Construction ", value: 22 },
    { name: "Consumer Services", value: 22.2 },
    { name: "Telecommunication", value: 13.6 },
  ],
  [
    { name: "Realty", value: 33.8 },
    { name: "Utilities", value: 25 },
    { name: "Media Entertainment & Publication", value: 14 },
    { name: "Capital Goods", value: 38 },
    { name: "FMCG", value: 21.7 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Information Technology", value: 18.9 },
    { name: "Diversified", value: 33.3 },
    { name: "Services", value: 23.9 },
    { name: "Healthcare", value: 28.2 },
    { name: "Power", value: 35.1 },
    { name: "Auto", value: 36.5 },
    { name: "Textiles", value: 16.9 },
    { name: "Chemicals", value: 19.4 },
    { name: "Metals & Mining", value: 30.2 },
    { name: "Construction Materials", value: 29.7 },
    { name: "Consumer Durables", value: 22.1 },
    { name: "Oil, Gas & Consumable fuels", value: 29.3 },
    { name: "Financial Services", value: 26.2 },
    { name: "Construction ", value: 28 },
    { name: "Consumer Services", value: 28.4 },
    { name: "Telecommunication", value: 13.6 },
  ],
  [
    { name: "Realty", value: 35.3 },
    { name: "Utilities", value: 50 },
    { name: "Media Entertainment & Publication", value: 12.3 },
    { name: "Capital Goods", value: 40 },
    { name: "FMCG", value: 17.5 },
    { name: "Forest Materials", value: 12.5 },
    { name: "Information Technology", value: 19.7 },
    { name: "Diversified", value: 26.7 },
    { name: "Services", value: 23.9 },
    { name: "Healthcare", value: 28.2 },
    { name: "Power", value: 40.5 },
    { name: "Auto", value: 36.5 },
    { name: "Textiles", value: 15.4 },
    { name: "Chemicals", value: 17.1 },
    { name: "Metals & Mining", value: 21.6 },
    { name: "Construction Materials", value: 21.6 },
    { name: "Consumer Durables", value: 20.8 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Financial Services", value: 24.4 },
    { name: "Construction ", value: 30.5 },
    { name: "Consumer Services", value: 29.6 },
    { name: "Telecommunication", value: 13.6 },
  ],
  [
    { name: "Realty", value: 42.6 },
    { name: "Utilities", value: 50 },
    { name: "Media Entertainment & Publication", value: 17.5 },
    { name: "Capital Goods", value: 45.5 },
    { name: "FMCG", value: 21 },
    { name: "Forest Materials", value: 9.4 },
    { name: "Information Technology", value: 22.8 },
    { name: "Diversified", value: 40 },
    { name: "Services", value: 28.3 },
    { name: "Healthcare", value: 32.8 },
    { name: "Power", value: 40.5 },
    { name: "Auto", value: 44.2 },
    { name: "Textiles", value: 16.2 },
    { name: "Chemicals", value: 18.8 },
    { name: "Metals & Mining", value: 27.6 },
    { name: "Construction Materials", value: 21.6 },
    { name: "Consumer Durables", value: 24.7 },
    { name: "Oil, Gas & Consumable fuels", value: 29.3 },
    { name: "Financial Services", value: 25.3 },
    { name: "Construction ", value: 35.4 },
    { name: "Consumer Services", value: 30.9 },
    { name: "Telecommunication", value: 13.6 },
  ],
  [
    { name: "Realty", value: 47.1 },
    { name: "Utilities", value: 50 },
    { name: "Media Entertainment & Publication", value: 14 },
    { name: "Capital Goods", value: 45 },
    { name: "FMCG", value: 21.7 },
    { name: "Forest Materials", value: 9.4 },
    { name: "Information Technology", value: 23.6 },
    { name: "Diversified", value: 33.3 },
    { name: "Services", value: 26.1 },
    { name: "Healthcare", value: 38.2 },
    { name: "Power", value: 45.9 },
    { name: "Auto", value: 53.8 },
    { name: "Textiles", value: 19.1 },
    { name: "Chemicals", value: 20 },
    { name: "Metals & Mining", value: 28.4 },
    { name: "Construction Materials", value: 24.3 },
    { name: "Consumer Durables", value: 28.6 },
    { name: "Oil, Gas & Consumable fuels", value: 31.7 },
    { name: "Financial Services", value: 31.2 },
    { name: "Construction ", value: 39 },
    { name: "Consumer Services", value: 33.3 },
    { name: "Telecommunication", value: 13.6 },
  ],
  [
    { name: "Realty", value: 70.6 },
    { name: "Utilities", value: 75 },
    { name: "Media Entertainment & Publication", value: 45.6 },
    { name: "Capital Goods", value: 67 },
    { name: "FMCG", value: 42 },
    { name: "Forest Materials", value: 37.5 },
    { name: "Information Technology", value: 46.5 },
    { name: "Diversified", value: 53.3 },
    { name: "Services", value: 52.2 },
    { name: "Healthcare", value: 61.1 },
    { name: "Power", value: 73 },
    { name: "Auto", value: 69.2 },
    { name: "Textiles", value: 39.7 },
    { name: "Chemicals", value: 44.1 },
    { name: "Metals & Mining", value: 56.9 },
    { name: "Construction Materials", value: 56.8 },
    { name: "Consumer Durables", value: 50.6 },
    { name: "Oil, Gas & Consumable fuels", value: 53.7 },
    { name: "Financial Services", value: 59.7 },
    { name: "Construction ", value: 59.8 },
    { name: "Consumer Services", value: 54.3 },
    { name: "Telecommunication", value: 36.4 },
  ],
  [
    { name: "Realty", value: 80.9 },
    { name: "Utilities", value: 75 },
    { name: "Media Entertainment & Publication", value: 57.9 },
    { name: "Capital Goods", value: 79 },
    { name: "FMCG", value: 60.8 },
    { name: "Forest Materials", value: 62.5 },
    { name: "Information Technology", value: 61.4 },
    { name: "Diversified", value: 80 },
    { name: "Services", value: 65.2 },
    { name: "Healthcare", value: 69.5 },
    { name: "Power", value: 81.1 },
    { name: "Auto", value: 77.9 },
    { name: "Textiles", value: 58.1 },
    { name: "Chemicals", value: 67.1 },
    { name: "Metals & Mining", value: 76.7 },
    { name: "Construction Materials", value: 74.3 },
    { name: "Consumer Durables", value: 68.8 },
    { name: "Oil, Gas & Consumable fuels", value: 78 },
    { name: "Financial Services", value: 71.9 },
    { name: "Construction ", value: 73.2 },
    { name: "Consumer Services", value: 65.4 },
    { name: "Telecommunication", value: 59.1 },
  ],
  [
    { name: "Realty", value: 83.8 },
    { name: "Utilities", value: 75 },
    { name: "Media Entertainment & Publication", value: 77.2 },
    { name: "Capital Goods", value: 88 },
    { name: "FMCG", value: 73.4 },
    { name: "Forest Materials", value: 84.4 },
    { name: "Information Technology", value: 74.8 },
    { name: "Diversified", value: 73.3 },
    { name: "Services", value: 80.4 },
    { name: "Healthcare", value: 77.1 },
    { name: "Power", value: 97.3 },
    { name: "Auto", value: 83.7 },
    { name: "Textiles", value: 71.3 },
    { name: "Chemicals", value: 82.4 },
    { name: "Metals & Mining", value: 84.5 },
    { name: "Construction Materials", value: 90.5 },
    { name: "Consumer Durables", value: 83.1 },
    { name: "Oil, Gas & Consumable fuels", value: 82.9 },
    { name: "Financial Services", value: 78.7 },
    { name: "Construction ", value: 86.6 },
    { name: "Consumer Services", value: 74.1 },
    { name: "Telecommunication", value: 72.7 },
  ],
  [
    { name: "Realty", value: 89.7 },
    { name: "Utilities", value: 100 },
    { name: "Media Entertainment & Publication", value: 77.2 },
    { name: "Capital Goods", value: 89.5 },
    { name: "FMCG", value: 74.8 },
    { name: "Forest Materials", value: 84.4 },
    { name: "Information Technology", value: 81.1 },
    { name: "Diversified", value: 86.7 },
    { name: "Services", value: 89.1 },
    { name: "Healthcare", value: 75.6 },
    { name: "Power", value: 97.3 },
    { name: "Auto", value: 82.7 },
    { name: "Textiles", value: 79.4 },
    { name: "Chemicals", value: 85.3 },
    { name: "Metals & Mining", value: 90.5 },
    { name: "Construction Materials", value: 89.2 },
    { name: "Consumer Durables", value: 89.6 },
    { name: "Oil, Gas & Consumable fuels", value: 85.4 },
    { name: "Financial Services", value: 82.8 },
    { name: "Construction ", value: 87.8 },
    { name: "Consumer Services", value: 80.2 },
    { name: "Telecommunication", value: 86.4 },
  ],
  [
    { name: "Realty", value: 94.1 },
    { name: "Utilities", value: 100 },
    { name: "Media Entertainment & Publication", value: 78.9 },
    { name: "Capital Goods", value: 90 },
    { name: "FMCG", value: 81.8 },
    { name: "Forest Materials", value: 87.5 },
    { name: "Information Technology", value: 81.9 },
    { name: "Diversified", value: 86.7 },
    { name: "Services", value: 93.5 },
    { name: "Healthcare", value: 81.7 },
    { name: "Power", value: 97.3 },
    { name: "Auto", value: 83.7 },
    { name: "Textiles", value: 80.9 },
    { name: "Chemicals", value: 87.6 },
    { name: "Metals & Mining", value: 90.5 },
    { name: "Construction Materials", value: 87.8 },
    { name: "Consumer Durables", value: 93.5 },
    { name: "Oil, Gas & Consumable fuels", value: 82.9 },
    { name: "Financial Services", value: 85.1 },
    { name: "Construction ", value: 87.8 },
    { name: "Consumer Services", value: 82.7 },
    { name: "Telecommunication", value: 81.8 },
  ],
  [
    { name: "Realty", value: 92.6 },
    { name: "Utilities", value: 100 },
    { name: "Media Entertainment & Publication", value: 68.4 },
    { name: "Capital Goods", value: 90.5 },
    { name: "FMCG", value: 74.8 },
    { name: "Forest Materials", value: 84.4 },
    { name: "Information Technology", value: 81.1 },
    { name: "Diversified", value: 86.7 },
    { name: "Services", value: 84.8 },
    { name: "Healthcare", value: 81.7 },
    { name: "Power", value: 91.9 },
    { name: "Auto", value: 81.7 },
    { name: "Textiles", value: 78.7 },
    { name: "Chemicals", value: 86.5 },
    { name: "Metals & Mining", value: 88.8 },
    { name: "Construction Materials", value: 91.9 },
    { name: "Consumer Durables", value: 88.3 },
    { name: "Oil, Gas & Consumable fuels", value: 87.8 },
    { name: "Financial Services", value: 83.7 },
    { name: "Construction ", value: 86.6 },
    { name: "Consumer Services", value: 75.3 },
    { name: "Telecommunication", value: 72.7 },
  ],
  [
    { name: "Realty", value: 88.2 },
    { name: "Utilities", value: 100 },
    { name: "Media Entertainment & Publication", value: 56.1 },
    { name: "Capital Goods", value: 83 },
    { name: "FMCG", value: 69.9 },
    { name: "Forest Materials", value: 71.9 },
    { name: "Information Technology", value: 74.8 },
    { name: "Diversified", value: 73.3 },
    { name: "Services", value: 82.6 },
    { name: "Healthcare", value: 77.1 },
    { name: "Power", value: 86.5 },
    { name: "Auto", value: 79.8 },
    { name: "Textiles", value: 67.6 },
    { name: "Chemicals", value: 75.9 },
    { name: "Metals & Mining", value: 82.8 },
    { name: "Construction Materials", value: 79.7 },
    { name: "Consumer Durables", value: 74 },
    { name: "Oil, Gas & Consumable fuels", value: 75.6 },
    { name: "Financial Services", value: 79.6 },
    { name: "Construction ", value: 82.9 },
    { name: "Consumer Services", value: 71.6 },
    { name: "Telecommunication", value: 63.6 },
  ],
  [
    { name: "Realty", value: 82.4 },
    { name: "Utilities", value: 100 },
    { name: "Media Entertainment & Publication", value: 59.6 },
    { name: "Capital Goods", value: 83.5 },
    { name: "FMCG", value: 65.7 },
    { name: "Forest Materials", value: 71.9 },
    { name: "Information Technology", value: 66.9 },
    { name: "Diversified", value: 73.3 },
    { name: "Services", value: 65.2 },
    { name: "Healthcare", value: 71.8 },
    { name: "Power", value: 86.5 },
    { name: "Auto", value: 75 },
    { name: "Textiles", value: 66.9 },
    { name: "Chemicals", value: 84.1 },
    { name: "Metals & Mining", value: 81.9 },
    { name: "Construction Materials", value: 74.3 },
    { name: "Consumer Durables", value: 76.6 },
    { name: "Oil, Gas & Consumable fuels", value: 78 },
    { name: "Financial Services", value: 79.2 },
    { name: "Construction ", value: 78 },
    { name: "Consumer Services", value: 70.4 },
    { name: "Telecommunication", value: 54.5 },
  ],
  [
    { name: "Realty", value: 72.1 },
    { name: "Utilities", value: 75 },
    { name: "Media Entertainment & Publication", value: 45.6 },
    { name: "Capital Goods", value: 76 },
    { name: "FMCG", value: 58.7 },
    { name: "Forest Materials", value: 59.4 },
    { name: "Information Technology", value: 59.8 },
    { name: "Diversified", value: 73.3 },
    { name: "Services", value: 65.2 },
    { name: "Healthcare", value: 66.4 },
    { name: "Power", value: 73 },
    { name: "Auto", value: 68.3 },
    { name: "Textiles", value: 61 },
    { name: "Chemicals", value: 77.6 },
    { name: "Metals & Mining", value: 72.4 },
    { name: "Construction Materials", value: 55.4 },
    { name: "Consumer Durables", value: 53.2 },
    { name: "Oil, Gas & Consumable fuels", value: 68.3 },
    { name: "Financial Services", value: 68.8 },
    { name: "Construction ", value: 67.1 },
    { name: "Consumer Services", value: 66.7 },
    { name: "Telecommunication", value: 40.9 },
  ],
  [
    { name: "Realty", value: 54.4 },
    { name: "Utilities", value: 50 },
    { name: "Media Entertainment & Publication", value: 28.1 },
    { name: "Capital Goods", value: 52.5 },
    { name: "FMCG", value: 37.1 },
    { name: "Forest Materials", value: 37.5 },
    { name: "Information Technology", value: 40.2 },
    { name: "Diversified", value: 60 },
    { name: "Services", value: 41.3 },
    { name: "Healthcare", value: 43.5 },
    { name: "Power", value: 37.8 },
    { name: "Auto", value: 47.1 },
    { name: "Textiles", value: 35.3 },
    { name: "Chemicals", value: 50 },
    { name: "Metals & Mining", value: 53.4 },
    { name: "Construction Materials", value: 33.8 },
    { name: "Consumer Durables", value: 37.7 },
    { name: "Oil, Gas & Consumable fuels", value: 58.5 },
    { name: "Financial Services", value: 44.3 },
    { name: "Construction ", value: 39 },
    { name: "Consumer Services", value: 35.8 },
    { name: "Telecommunication", value: 22.7 },
  ],
  [
    { name: "Realty", value: 55.9 },
    { name: "Utilities", value: 100 },
    { name: "Media Entertainment & Publication", value: 33.3 },
    { name: "Capital Goods", value: 62 },
    { name: "FMCG", value: 44.8 },
    { name: "Forest Materials", value: 40.6 },
    { name: "Information Technology", value: 43.3 },
    { name: "Diversified", value: 60 },
    { name: "Services", value: 45.7 },
    { name: "Healthcare", value: 58 },
    { name: "Power", value: 54.1 },
    { name: "Auto", value: 58.7 },
    { name: "Textiles", value: 41.2 },
    { name: "Chemicals", value: 58.2 },
    { name: "Metals & Mining", value: 52.6 },
    { name: "Construction Materials", value: 39.2 },
    { name: "Consumer Durables", value: 46.8 },
    { name: "Oil, Gas & Consumable fuels", value: 68.3 },
    { name: "Financial Services", value: 44.3 },
    { name: "Construction ", value: 48.8 },
    { name: "Consumer Services", value: 50.6 },
    { name: "Telecommunication", value: 27.3 },
  ],
  [
    { name: "Realty", value: 54.4 },
    { name: "Utilities", value: 75 },
    { name: "Media Entertainment & Publication", value: 38.6 },
    { name: "Capital Goods", value: 68 },
    { name: "FMCG", value: 35.7 },
    { name: "Forest Materials", value: 43.8 },
    { name: "Information Technology", value: 40.2 },
    { name: "Diversified", value: 60 },
    { name: "Services", value: 43.5 },
    { name: "Healthcare", value: 51.1 },
    { name: "Power", value: 51.4 },
    { name: "Auto", value: 59.6 },
    { name: "Textiles", value: 43.4 },
    { name: "Chemicals", value: 56.5 },
    { name: "Metals & Mining", value: 51.7 },
    { name: "Construction Materials", value: 33.8 },
    { name: "Consumer Durables", value: 45.5 },
    { name: "Oil, Gas & Consumable fuels", value: 58.5 },
    { name: "Financial Services", value: 45.2 },
    { name: "Construction ", value: 48.8 },
    { name: "Consumer Services", value: 42 },
    { name: "Telecommunication", value: 40.9 },
  ],
];
