export const data_52W = [
  [
    { name: "Construction ", value: 14.5 },
    { name: "Healthcare", value: 15.2 },
    { name: "Oil, Gas & Consumable fuels", value: 19.5 },
    { name: "Capital Goods", value: 22.2 },
    { name: "Telecommunication", value: 9.1 },
    { name: "Auto", value: 30.8 },
    { name: "Realty", value: 20.0 },
    { name: "Media Entertainment & Publication", value: 7.0 },
    { name: "Consumer Services", value: 13.3 },
    { name: "Forest Materials", value: 21.9 },

    { name: "Construction", value: 16.2 },
    { name: "Financial Services", value: 21.5 },
    { name: "Information Technology", value: 11.0 },

    { name: "Power", value: 13.5 },
    { name: "Metals & Mining", value: 7.6 },
    { name: "FMCG", value: 9.5 },
    { name: "Textiles", value: 12.6 },
    { name: "Consumer Durables", value: 18.2 },
    { name: "Chemicals", value: 17.5 },
    { name: "Services", value: 8.3 },
  ],
  [
    { name: "Construction ", value: 22.9 },
    { name: "Healthcare", value: 16.7 },
    { name: "Oil, Gas & Consumable fuels", value: 24.4 },
    { name: "Capital Goods", value: 31.0 },
    { name: "Telecommunication", value: 9.1 },
    { name: "Auto", value: 27.9 },
    { name: "Realty", value: 25.7 },
    { name: "Media Entertainment & Publication", value: 7.0 },
    { name: "Consumer Services", value: 10.8 },
    { name: "Forest Materials", value: 12.5 },

    { name: "Construction", value: 21.6 },
    { name: "Financial Services", value: 21.5 },
    { name: "Information Technology", value: 15.0 },

    { name: "Power", value: 18.9 },
    { name: "Metals & Mining", value: 14.4 },
    { name: "FMCG", value: 13.5 },
    { name: "Textiles", value: 11.1 },
    { name: "Consumer Durables", value: 15.6 },
    { name: "Chemicals", value: 17.5 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 25.3 },
    { name: "Healthcare", value: 22.0 },
    { name: "Oil, Gas & Consumable fuels", value: 24.4 },
    { name: "Capital Goods", value: 31.0 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 27.9 },
    { name: "Realty", value: 20.0 },
    { name: "Media Entertainment & Publication", value: 8.8 },
    { name: "Consumer Services", value: 13.3 },
    { name: "Forest Materials", value: 9.4 },

    { name: "Construction", value: 21.6 },
    { name: "Financial Services", value: 21.1 },
    { name: "Information Technology", value: 18.9 },

    { name: "Power", value: 16.2 },
    { name: "Metals & Mining", value: 15.3 },
    { name: "FMCG", value: 11.5 },
    { name: "Textiles", value: 12.6 },
    { name: "Consumer Durables", value: 14.3 },
    { name: "Chemicals", value: 17.0 },
    { name: "Services", value: 12.5 },
  ],
  [
    { name: "Construction ", value: 26.5 },
    { name: "Healthcare", value: 25.8 },
    { name: "Oil, Gas & Consumable fuels", value: 31.7 },
    { name: "Capital Goods", value: 29.6 },
    { name: "Telecommunication", value: 18.2 },
    { name: "Auto", value: 32.7 },
    { name: "Realty", value: 22.9 },
    { name: "Media Entertainment & Publication", value: 8.8 },
    { name: "Consumer Services", value: 13.3 },
    { name: "Forest Materials", value: 9.4 },

    { name: "Construction", value: 17.6 },
    { name: "Financial Services", value: 22.0 },
    { name: "Information Technology", value: 16.5 },

    { name: "Power", value: 16.2 },
    { name: "Metals & Mining", value: 16.1 },
    { name: "FMCG", value: 10.1 },
    { name: "Textiles", value: 12.6 },
    { name: "Consumer Durables", value: 14.3 },
    { name: "Chemicals", value: 20.5 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 21.7 },
    { name: "Healthcare", value: 22.7 },
    { name: "Oil, Gas & Consumable fuels", value: 31.7 },
    { name: "Capital Goods", value: 23.2 },
    { name: "Telecommunication", value: 9.1 },
    { name: "Auto", value: 25.0 },
    { name: "Realty", value: 20.0 },
    { name: "Media Entertainment & Publication", value: 10.5 },
    { name: "Consumer Services", value: 9.6 },
    { name: "Forest Materials", value: 12.5 },

    { name: "Construction", value: 12.2 },
    { name: "Financial Services", value: 17.9 },
    { name: "Information Technology", value: 15.0 },

    { name: "Power", value: 16.2 },
    { name: "Metals & Mining", value: 16.1 },
    { name: "FMCG", value: 14.9 },
    { name: "Textiles", value: 6.7 },
    { name: "Consumer Durables", value: 11.7 },
    { name: "Chemicals", value: 19.3 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 26.5 },
    { name: "Healthcare", value: 26.5 },
    { name: "Oil, Gas & Consumable fuels", value: 29.3 },
    { name: "Capital Goods", value: 18.7 },
    { name: "Telecommunication", value: 0.0 },
    { name: "Auto", value: 29.8 },
    { name: "Realty", value: 12.9 },
    { name: "Media Entertainment & Publication", value: 12.3 },
    { name: "Consumer Services", value: 10.8 },
    { name: "Forest Materials", value: 6.2 },

    { name: "Construction", value: 12.2 },
    { name: "Financial Services", value: 17.0 },
    { name: "Information Technology", value: 15.7 },

    { name: "Power", value: 18.9 },
    { name: "Metals & Mining", value: 14.4 },
    { name: "FMCG", value: 16.2 },
    { name: "Textiles", value: 6.7 },
    { name: "Consumer Durables", value: 11.7 },
    { name: "Chemicals", value: 19.3 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 14.5 },
    { name: "Healthcare", value: 21.2 },
    { name: "Oil, Gas & Consumable fuels", value: 19.5 },
    { name: "Capital Goods", value: 12.3 },
    { name: "Telecommunication", value: 0.0 },
    { name: "Auto", value: 27.9 },
    { name: "Realty", value: 10.0 },
    { name: "Media Entertainment & Publication", value: 12.3 },
    { name: "Consumer Services", value: 10.8 },
    { name: "Forest Materials", value: 3.1 },

    { name: "Construction", value: 9.5 },
    { name: "Financial Services", value: 14.3 },
    { name: "Information Technology", value: 11.0 },

    { name: "Power", value: 13.5 },
    { name: "Metals & Mining", value: 11.0 },
    { name: "FMCG", value: 12.2 },
    { name: "Textiles", value: 11.1 },
    { name: "Consumer Durables", value: 10.4 },
    { name: "Chemicals", value: 11.1 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 22.9 },
    { name: "Healthcare", value: 22.7 },
    { name: "Oil, Gas & Consumable fuels", value: 22.0 },
    { name: "Capital Goods", value: 20.7 },
    { name: "Telecommunication", value: 4.5 },
    { name: "Auto", value: 26.9 },
    { name: "Realty", value: 10.0 },
    { name: "Media Entertainment & Publication", value: 14.0 },
    { name: "Consumer Services", value: 10.8 },
    { name: "Forest Materials", value: 3.1 },

    { name: "Construction", value: 13.5 },
    { name: "Financial Services", value: 21.1 },
    { name: "Information Technology", value: 15.0 },

    { name: "Power", value: 16.2 },
    { name: "Metals & Mining", value: 10.2 },
    { name: "FMCG", value: 15.5 },
    { name: "Textiles", value: 11.9 },
    { name: "Consumer Durables", value: 16.9 },
    { name: "Chemicals", value: 12.9 },
    { name: "Services", value: 14.6 },
  ],
  [
    { name: "Construction ", value: 14.5 },
    { name: "Healthcare", value: 19.7 },
    { name: "Oil, Gas & Consumable fuels", value: 19.5 },
    { name: "Capital Goods", value: 13.8 },
    { name: "Telecommunication", value: 9.1 },
    { name: "Auto", value: 20.2 },
    { name: "Realty", value: 7.1 },
    { name: "Media Entertainment & Publication", value: 12.3 },
    { name: "Consumer Services", value: 8.4 },
    { name: "Forest Materials", value: 3.1 },

    { name: "Construction", value: 9.5 },
    { name: "Financial Services", value: 15.2 },
    { name: "Information Technology", value: 15.7 },

    { name: "Power", value: 21.6 },
    { name: "Metals & Mining", value: 11.0 },
    { name: "FMCG", value: 11.5 },
    { name: "Textiles", value: 8.9 },
    { name: "Consumer Durables", value: 16.9 },
    { name: "Chemicals", value: 11.7 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 12.0 },
    { name: "Healthcare", value: 22.7 },
    { name: "Oil, Gas & Consumable fuels", value: 26.8 },
    { name: "Capital Goods", value: 12.8 },
    { name: "Telecommunication", value: 4.5 },
    { name: "Auto", value: 24.0 },
    { name: "Realty", value: 11.4 },
    { name: "Media Entertainment & Publication", value: 14.0 },
    { name: "Consumer Services", value: 10.8 },
    { name: "Forest Materials", value: 6.2 },

    { name: "Construction", value: 10.8 },
    { name: "Financial Services", value: 17.5 },
    { name: "Information Technology", value: 19.7 },

    { name: "Power", value: 27.0 },
    { name: "Metals & Mining", value: 9.3 },
    { name: "FMCG", value: 14.9 },
    { name: "Textiles", value: 8.9 },
    { name: "Consumer Durables", value: 14.3 },
    { name: "Chemicals", value: 11.1 },
    { name: "Services", value: 6.2 },
  ],
  [
    { name: "Construction ", value: 9.6 },
    { name: "Healthcare", value: 23.5 },
    { name: "Oil, Gas & Consumable fuels", value: 26.8 },
    { name: "Capital Goods", value: 11.3 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 23.1 },
    { name: "Realty", value: 7.1 },
    { name: "Media Entertainment & Publication", value: 10.5 },
    { name: "Consumer Services", value: 9.6 },
    { name: "Forest Materials", value: 3.1 },

    { name: "Construction", value: 16.2 },
    { name: "Financial Services", value: 15.2 },
    { name: "Information Technology", value: 17.3 },

    { name: "Power", value: 18.9 },
    { name: "Metals & Mining", value: 11.0 },
    { name: "FMCG", value: 14.9 },
    { name: "Textiles", value: 12.6 },
    { name: "Consumer Durables", value: 14.3 },
    { name: "Chemicals", value: 9.9 },
    { name: "Services", value: 10.4 },
  ],
  [
    { name: "Construction ", value: 6.0 },
    { name: "Healthcare", value: 17.4 },
    { name: "Oil, Gas & Consumable fuels", value: 24.4 },
    { name: "Capital Goods", value: 5.9 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 16.3 },
    { name: "Realty", value: 7.1 },
    { name: "Media Entertainment & Publication", value: 12.3 },
    { name: "Consumer Services", value: 8.4 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Construction", value: 10.8 },
    { name: "Financial Services", value: 13.5 },
    { name: "Information Technology", value: 12.6 },
    { name: "Power", value: 13.5 },
    { name: "Metals & Mining", value: 5.1 },
    { name: "FMCG", value: 11.5 },
    { name: "Textiles", value: 8.1 },
    { name: "Consumer Durables", value: 9.1 },
    { name: "Chemicals", value: 8.2 },
    { name: "Services", value: 2.1 },
  ],
  [
    { name: "Construction ", value: 3.6 },
    { name: "Healthcare", value: 9.8 },
    { name: "Oil, Gas & Consumable fuels", value: 9.8 },
    { name: "Capital Goods", value: 2.0 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 3.8 },
    { name: "Realty", value: 5.7 },
    { name: "Media Entertainment & Publication", value: 8.8 },
    { name: "Consumer Services", value: 2.4 },
    { name: "Forest Materials", value: 0.0 },
    { name: "Construction", value: 6.8 },
    { name: "Financial Services", value: 8.1 },
    { name: "Information Technology", value: 8.7 },
    { name: "Power", value: 5.4 },
    { name: "Metals & Mining", value: 1.7 },
    { name: "FMCG", value: 7.4 },
    { name: "Textiles", value: 5.2 },
    { name: "Consumer Durables", value: 7.8 },
    { name: "Chemicals", value: 4.7 },
    { name: "Services", value: 4.2 },
  ],
  [
    { name: "Construction ", value: 6.0 },
    { name: "Healthcare", value: 15.2 },
    { name: "Oil, Gas & Consumable fuels", value: 9.8 },
    { name: "Capital Goods", value: 2.0 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 6.7 },
    { name: "Realty", value: 5.7 },
    { name: "Media Entertainment & Publication", value: 5.3 },
    { name: "Consumer Services", value: 6.0 },
    { name: "Forest Materials", value: 0.0 },
    { name: "Construction", value: 10.8 },
    { name: "Financial Services", value: 8.5 },
    { name: "Information Technology", value: 8.7 },
    { name: "Power", value: 5.4 },
    { name: "Metals & Mining", value: 2.5 },
    { name: "FMCG", value: 6.1 },
    { name: "Textiles", value: 6.7 },
    { name: "Consumer Durables", value: 10.4 },
    { name: "Chemicals", value: 10.5 },
    { name: "Services", value: 6.2 },
  ],
  [
    { name: "Construction ", value: 7.2 },
    { name: "Healthcare", value: 19.7 },
    { name: "Oil, Gas & Consumable fuels", value: 4.9 },
    { name: "Capital Goods", value: 3.0 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 6.7 },
    { name: "Realty", value: 1.4 },
    { name: "Media Entertainment & Publication", value: 5.3 },
    { name: "Consumer Services", value: 4.8 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Construction", value: 12.2 },
    { name: "Financial Services", value: 4.0 },
    { name: "Information Technology", value: 9.4 },
    { name: "Power", value: 8.1 },
    { name: "Metals & Mining", value: 4.2 },
    { name: "FMCG", value: 10.1 },
    { name: "Textiles", value: 8.1 },
    { name: "Consumer Durables", value: 16.9 },
    { name: "Chemicals", value: 9.9 },
    { name: "Services", value: 4.2 },
  ],
  [
    { name: "Construction ", value: 10.8 },
    { name: "Healthcare", value: 26.5 },
    { name: "Oil, Gas & Consumable fuels", value: 14.6 },
    { name: "Capital Goods", value: 7.4 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 11.5 },
    { name: "Realty", value: 2.9 },
    { name: "Media Entertainment & Publication", value: 8.8 },
    { name: "Consumer Services", value: 9.6 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Construction", value: 13.5 },
    { name: "Financial Services", value: 11.2 },
    { name: "Information Technology", value: 13.4 },
    { name: "Power", value: 8.1 },
    { name: "Metals & Mining", value: 11.0 },
    { name: "FMCG", value: 16.2 },
    { name: "Textiles", value: 14.1 },
    { name: "Consumer Durables", value: 18.2 },
    { name: "Chemicals", value: 17.5 },
    { name: "Services", value: 8.3 },
  ],
  [
    { name: "Construction ", value: 10.8 },
    { name: "Healthcare", value: 28.0 },
    { name: "Oil, Gas & Consumable fuels", value: 19.5 },
    { name: "Capital Goods", value: 10.3 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 12.5 },
    { name: "Realty", value: 8.6 },
    { name: "Media Entertainment & Publication", value: 10.5 },
    { name: "Consumer Services", value: 6.0 },
    { name: "Forest Materials", value: 6.2 },
    { name: "Construction", value: 12.2 },
    { name: "Financial Services", value: 11.7 },
    { name: "Information Technology", value: 11.8 },
    { name: "Power", value: 10.8 },
    { name: "Metals & Mining", value: 6.8 },
    { name: "FMCG", value: 14.2 },
    { name: "Textiles", value: 16.3 },
    { name: "Consumer Durables", value: 15.6 },
    { name: "Chemicals", value: 18.1 },
    { name: "Services", value: 8.3 },
  ],
  [
    { name: "Construction ", value: 16.9 },
    { name: "Healthcare", value: 34.1 },
    { name: "Oil, Gas & Consumable fuels", value: 24.4 },
    { name: "Capital Goods", value: 9.9 },
    { name: "Telecommunication", value: 18.2 },
    { name: "Auto", value: 20.2 },
    { name: "Realty", value: 11.4 },
    { name: "Media Entertainment & Publication", value: 10.5 },
    { name: "Consumer Services", value: 8.4 },
    { name: "Forest Materials", value: 6.2 },
    { name: "Construction", value: 14.9 },
    { name: "Financial Services", value: 14.8 },
    { name: "Information Technology", value: 15.7 },
    { name: "Power", value: 18.9 },
    { name: "Metals & Mining", value: 10.2 },
    { name: "FMCG", value: 14.9 },
    { name: "Textiles", value: 15.6 },
    { name: "Consumer Durables", value: 16.9 },
    { name: "Chemicals", value: 18.7 },
    { name: "Services", value: 12.5 },
  ],
  [
    { name: "Construction ", value: 20.5 },
    { name: "Healthcare", value: 32.6 },
    { name: "Oil, Gas & Consumable fuels", value: 26.8 },
    { name: "Capital Goods", value: 12.8 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 25.0 },
    { name: "Realty", value: 10.0 },
    { name: "Media Entertainment & Publication", value: 14.0 },
    { name: "Consumer Services", value: 10.8 },
    { name: "Forest Materials", value: 6.2 },
    { name: "Construction", value: 16.2 },
    { name: "Financial Services", value: 20.2 },
    { name: "Information Technology", value: 16.5 },
    { name: "Power", value: 18.9 },
    { name: "Metals & Mining", value: 12.7 },
    { name: "FMCG", value: 16.9 },
    { name: "Textiles", value: 17.8 },
    { name: "Consumer Durables", value: 16.9 },
    { name: "Chemicals", value: 20.5 },
    { name: "Services", value: 16.7 },
  ],
  [
    { name: "Construction ", value: 21.7 },
    { name: "Healthcare", value: 30.3 },
    { name: "Oil, Gas & Consumable fuels", value: 29.3 },
    { name: "Capital Goods", value: 15.8 },
    { name: "Telecommunication", value: 13.6 },
    { name: "Auto", value: 26.9 },
    { name: "Realty", value: 10.0 },
    { name: "Media Entertainment & Publication", value: 15.8 },
    { name: "Consumer Services", value: 12.0 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Construction", value: 18.9 },
    { name: "Financial Services", value: 21.1 },
    { name: "Information Technology", value: 16.5 },
    { name: "Power", value: 24.3 },
    { name: "Metals & Mining", value: 11.9 },
    { name: "FMCG", value: 19.6 },
    { name: "Textiles", value: 18.5 },
    { name: "Consumer Durables", value: 18.2 },
    { name: "Chemicals", value: 26.9 },
    { name: "Services", value: 14.6 },
  ],
  [
    { name: "Construction ", value: 22.9 },
    { name: "Healthcare", value: 36.4 },
    { name: "Oil, Gas & Consumable fuels", value: 24.4 },
    { name: "Capital Goods", value: 14.8 },
    { name: "Telecommunication", value: 18.2 },
    { name: "Auto", value: 27.9 },
    { name: "Realty", value: 8.6 },
    { name: "Media Entertainment & Publication", value: 14.0 },
    { name: "Consumer Services", value: 12.0 },
    { name: "Forest Materials", value: 6.2 },
    { name: "Construction", value: 17.6 },
    { name: "Financial Services", value: 20.6 },
    { name: "Information Technology", value: 15.0 },
    { name: "Power", value: 27.0 },
    { name: "Metals & Mining", value: 11.0 },
    { name: "FMCG", value: 16.2 },
    { name: "Textiles", value: 20.7 },
    { name: "Consumer Durables", value: 15.6 },
    { name: "Chemicals", value: 21.1 },
    { name: "Services", value: 12.5 },
  ],
  [
    { name: "Construction ", value: 10.8 },
    { name: "Healthcare", value: 32.6 },
    { name: "Oil, Gas & Consumable fuels", value: 26.8 },
    { name: "Capital Goods", value: 10.8 },
    { name: "Telecommunication", value: 4.5 },
    { name: "Auto", value: 18.3 },
    { name: "Realty", value: 8.6 },
    { name: "Media Entertainment & Publication", value: 10.5 },
    { name: "Consumer Services", value: 8.4 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Construction", value: 12.2 },
    { name: "Financial Services", value: 14.8 },
    { name: "Information Technology", value: 15.0 },
    { name: "Power", value: 24.3 },
    { name: "Metals & Mining", value: 13.6 },
    { name: "FMCG", value: 15.5 },
    { name: "Textiles", value: 11.1 },
    { name: "Consumer Durables", value: 16.9 },
    { name: "Chemicals", value: 18.7 },
    { name: "Services", value: 8.3 },
  ],
  [
    { name: "Construction ", value: 10.8 },
    { name: "Healthcare", value: 34.1 },
    { name: "Oil, Gas & Consumable fuels", value: 22.0 },
    { name: "Capital Goods", value: 12.3 },
    { name: "Telecommunication", value: 9.1 },
    { name: "Auto", value: 12.5 },
    { name: "Realty", value: 7.1 },
    { name: "Media Entertainment & Publication", value: 14.0 },
    { name: "Consumer Services", value: 3.6 },
    { name: "Forest Materials", value: 3.1 },
    { name: "Construction", value: 10.8 },
    { name: "Financial Services", value: 11.7 },
    { name: "Information Technology", value: 11.8 },
    { name: "Power", value: 27.0 },
    { name: "Metals & Mining", value: 9.3 },
    { name: "FMCG", value: 11.5 },
    { name: "Textiles", value: 8.9 },
    { name: "Consumer Durables", value: 19.5 },
    { name: "Chemicals", value: 21.6 },
    { name: "Services", value: 4.2 },
  ],
];
