export const data_RS70 = [
  [
    { name: "Realty", value: 57.1 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 54.8 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 70.3 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 28.6 },
    { name: "Oil, Gas & Consumable fuels", value: 31.7 },
    { name: "Media Entertainment & Publication", value: 16.1 },
    { name: "FMCG", value: 18.4 },
    { name: "Consumer Services", value: 18.3 },
    { name: "Telecommunication", value: 36.4 },
    { name: "Healthcare", value: 17.4 },
    { name: "Textiles", value: 15.6 },
    { name: "Auto", value: 32.0 },
    { name: "Metals & Mining", value: 37.0 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 46.0 },
    { name: "Chemicals", value: 19.3 },
    { name: "Financial Services", value: 26.9 },
  ],
  [
    { name: "Realty", value: 55.7 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 20.3 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 27.3 },
    { name: "Information Technology", value: 29.4 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 17.0 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 36.4 },
    { name: "Healthcare", value: 15.2 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 33.0 },
    { name: "Metals & Mining", value: 36.1 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 47.0 },
    { name: "Chemicals", value: 18.7 },
    { name: "Financial Services", value: 27.8 },
  ],
  [
    { name: "Realty", value: 54.3 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 31.0 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 16.1 },
    { name: "FMCG", value: 15.6 },
    { name: "Consumer Services", value: 18.3 },
    { name: "Telecommunication", value: 40.9 },
    { name: "Healthcare", value: 14.4 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 33.0 },
    { name: "Metals & Mining", value: 35.3 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 46.5 },
    { name: "Chemicals", value: 17.0 },
    { name: "Financial Services", value: 30.5 },
  ],
  [
    { name: "Realty", value: 54.3 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 54.8 },
    { name: "Construction", value: 23.0 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 27.3 },
    { name: "Information Technology", value: 28.6 },
    { name: "Oil, Gas & Consumable fuels", value: 36.6 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 16.3 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 40.9 },
    { name: "Healthcare", value: 12.9 },
    { name: "Textiles", value: 18.5 },
    { name: "Auto", value: 33.0 },
    { name: "Metals & Mining", value: 37.8 },
    { name: "Forest Materials", value: 12.5 },
    { name: "Capital Goods", value: 45.0 },
    { name: "Chemicals", value: 18.7 },
    { name: "Financial Services", value: 29.1 },
  ],
  [
    { name: "Realty", value: 52.9 },
    { name: "Services", value: 14.6 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 24.3 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 31.2 },
    { name: "Information Technology", value: 29.4 },
    { name: "Oil, Gas & Consumable fuels", value: 36.6 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 15.0 },
    { name: "Consumer Services", value: 15.9 },
    { name: "Telecommunication", value: 45.5 },
    { name: "Healthcare", value: 12.1 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 33.0 },
    { name: "Metals & Mining", value: 36.1 },
    { name: "Forest Materials", value: 12.5 },
    { name: "Capital Goods", value: 46.5 },
    { name: "Chemicals", value: 18.7 },
    { name: "Financial Services", value: 29.1 },
  ],
  [
    { name: "Realty", value: 51.4 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 56.0 },
    { name: "Construction", value: 25.7 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 31.2 },
    { name: "Information Technology", value: 30.2 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 14.3 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 36.4 },
    { name: "Healthcare", value: 14.4 },
    { name: "Textiles", value: 17.0 },
    { name: "Auto", value: 32.0 },
    { name: "Metals & Mining", value: 34.5 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 43.1 },
    { name: "Chemicals", value: 19.3 },
    { name: "Financial Services", value: 31.8 },
  ],
  [
    { name: "Realty", value: 52.9 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 56.0 },
    { name: "Construction", value: 25.7 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 29.9 },
    { name: "Information Technology", value: 31.7 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 21.4 },
    { name: "FMCG", value: 14.3 },
    { name: "Consumer Services", value: 19.5 },
    { name: "Telecommunication", value: 31.8 },
    { name: "Healthcare", value: 15.9 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 34.0 },
    { name: "Metals & Mining", value: 31.9 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 42.1 },
    { name: "Chemicals", value: 18.1 },
    { name: "Financial Services", value: 30.5 },
  ],
  [
    { name: "Realty", value: 52.9 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 54.8 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 29.9 },
    { name: "Information Technology", value: 32.5 },
    { name: "Oil, Gas & Consumable fuels", value: 31.7 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 16.3 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 31.8 },
    { name: "Healthcare", value: 14.4 },
    { name: "Textiles", value: 19.3 },
    { name: "Auto", value: 34.0 },
    { name: "Metals & Mining", value: 32.8 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 45.0 },
    { name: "Chemicals", value: 17.5 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 52.9 },
    { name: "Services", value: 14.6 },
    { name: "Construction ", value: 56.0 },
    { name: "Construction", value: 20.3 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 27.3 },
    { name: "Information Technology", value: 31.7 },
    { name: "Oil, Gas & Consumable fuels", value: 36.6 },
    { name: "Media Entertainment & Publication", value: 14.3 },
    { name: "FMCG", value: 14.3 },
    { name: "Consumer Services", value: 18.3 },
    { name: "Telecommunication", value: 22.7 },
    { name: "Healthcare", value: 14.4 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 34.0 },
    { name: "Metals & Mining", value: 34.5 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 47.0 },
    { name: "Chemicals", value: 17.5 },
    { name: "Financial Services", value: 30.9 },
  ],
  [
    { name: "Realty", value: 54.3 },
    { name: "Services", value: 14.6 },
    { name: "Construction ", value: 54.8 },
    { name: "Construction", value: 20.3 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 31.0 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 14.3 },
    { name: "FMCG", value: 17.0 },
    { name: "Consumer Services", value: 19.5 },
    { name: "Telecommunication", value: 22.7 },
    { name: "Healthcare", value: 15.9 },
    { name: "Textiles", value: 20.7 },
    { name: "Auto", value: 32.0 },
    { name: "Metals & Mining", value: 33.6 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 46.5 },
    { name: "Chemicals", value: 17.0 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 54.3 },
    { name: "Services", value: 14.6 },
    { name: "Construction ", value: 54.8 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 62.2 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 31.0 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 16.1 },
    { name: "FMCG", value: 16.3 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 27.3 },
    { name: "Healthcare", value: 18.2 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 31.1 },
    { name: "Metals & Mining", value: 36.1 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 47.0 },
    { name: "Chemicals", value: 16.4 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 55.7 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 23.0 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 27.3 },
    { name: "Information Technology", value: 32.5 },
    { name: "Oil, Gas & Consumable fuels", value: 36.6 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 16.3 },
    { name: "Consumer Services", value: 18.3 },
    { name: "Telecommunication", value: 31.8 },
    { name: "Healthcare", value: 18.2 },
    { name: "Textiles", value: 17.0 },
    { name: "Auto", value: 31.1 },
    { name: "Metals & Mining", value: 34.5 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 44.6 },
    { name: "Chemicals", value: 18.7 },
    { name: "Financial Services", value: 28.3 },
  ],
  [
    { name: "Realty", value: 52.9 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 20.3 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 28.6 },
    { name: "Information Technology", value: 31.7 },
    { name: "Oil, Gas & Consumable fuels", value: 36.6 },
    { name: "Media Entertainment & Publication", value: 16.1 },
    { name: "FMCG", value: 17.0 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 36.4 },
    { name: "Healthcare", value: 16.7 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 32.0 },
    { name: "Metals & Mining", value: 33.6 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 44.6 },
    { name: "Chemicals", value: 18.7 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 50.0 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 56.0 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 31.0 },
    { name: "Oil, Gas & Consumable fuels", value: 39.0 },
    { name: "Media Entertainment & Publication", value: 16.1 },
    { name: "FMCG", value: 19.7 },
    { name: "Consumer Services", value: 18.3 },
    { name: "Telecommunication", value: 31.8 },
    { name: "Healthcare", value: 17.4 },
    { name: "Textiles", value: 18.5 },
    { name: "Auto", value: 33.0 },
    { name: "Metals & Mining", value: 32.8 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 44.1 },
    { name: "Chemicals", value: 17.0 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 51.4 },
    { name: "Services", value: 12.5 },
    { name: "Construction ", value: 56.0 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 62.2 },
    { name: "Consumer Durables", value: 27.3 },
    { name: "Information Technology", value: 31.0 },
    { name: "Oil, Gas & Consumable fuels", value: 41.5 },
    { name: "Media Entertainment & Publication", value: 19.6 },
    { name: "FMCG", value: 19.7 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 27.3 },
    { name: "Healthcare", value: 16.7 },
    { name: "Textiles", value: 17.8 },
    { name: "Auto", value: 33.0 },
    { name: "Metals & Mining", value: 31.9 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 44.6 },
    { name: "Chemicals", value: 18.1 },
    { name: "Financial Services", value: 29.1 },
  ],
  [
    { name: "Realty", value: 57.1 },
    { name: "Services", value: 16.7 },
    { name: "Construction ", value: 56.0 },
    { name: "Construction", value: 20.3 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 27.3 },
    { name: "Information Technology", value: 34.1 },
    { name: "Oil, Gas & Consumable fuels", value: 34.1 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 17.7 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 27.3 },
    { name: "Healthcare", value: 15.2 },
    { name: "Textiles", value: 19.3 },
    { name: "Auto", value: 31.1 },
    { name: "Metals & Mining", value: 33.6 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 42.6 },
    { name: "Chemicals", value: 18.1 },
    { name: "Financial Services", value: 29.1 },
  ],
  [
    { name: "Realty", value: 54.3 },
    { name: "Services", value: 20.8 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 31.7 },
    { name: "Oil, Gas & Consumable fuels", value: 39.0 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 17.7 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 36.4 },
    { name: "Healthcare", value: 17.4 },
    { name: "Textiles", value: 18.5 },
    { name: "Auto", value: 31.1 },
    { name: "Metals & Mining", value: 31.1 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 43.6 },
    { name: "Chemicals", value: 17.0 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 57.1 },
    { name: "Services", value: 14.6 },
    { name: "Construction ", value: 53.6 },
    { name: "Construction", value: 23.0 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 34.1 },
    { name: "Oil, Gas & Consumable fuels", value: 39.0 },
    { name: "Media Entertainment & Publication", value: 14.3 },
    { name: "FMCG", value: 17.7 },
    { name: "Consumer Services", value: 17.1 },
    { name: "Telecommunication", value: 31.8 },
    { name: "Healthcare", value: 16.7 },
    { name: "Textiles", value: 18.5 },
    { name: "Auto", value: 34.0 },
    { name: "Metals & Mining", value: 29.4 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 41.6 },
    { name: "Chemicals", value: 18.7 },
    { name: "Financial Services", value: 30.5 },
  ],
  [
    { name: "Realty", value: 57.1 },
    { name: "Services", value: 14.6 },
    { name: "Construction ", value: 50.0 },
    { name: "Construction", value: 23.0 },
    { name: "Power", value: 67.6 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 34.1 },
    { name: "Oil, Gas & Consumable fuels", value: 41.5 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 17.0 },
    { name: "Consumer Services", value: 15.9 },
    { name: "Telecommunication", value: 31.8 },
    { name: "Healthcare", value: 18.9 },
    { name: "Textiles", value: 19.3 },
    { name: "Auto", value: 31.1 },
    { name: "Metals & Mining", value: 30.3 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 41.6 },
    { name: "Chemicals", value: 17.5 },
    { name: "Financial Services", value: 31.4 },
  ],
  [
    { name: "Realty", value: 55.7 },
    { name: "Services", value: 18.8 },
    { name: "Construction ", value: 52.4 },
    { name: "Construction", value: 23.0 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 24.7 },
    { name: "Information Technology", value: 34.9 },
    { name: "Oil, Gas & Consumable fuels", value: 43.9 },
    { name: "Media Entertainment & Publication", value: 16.1 },
    { name: "FMCG", value: 17.7 },
    { name: "Consumer Services", value: 15.9 },
    { name: "Telecommunication", value: 27.3 },
    { name: "Healthcare", value: 19.7 },
    { name: "Textiles", value: 20.0 },
    { name: "Auto", value: 31.1 },
    { name: "Metals & Mining", value: 31.9 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 40.6 },
    { name: "Chemicals", value: 17.5 },
    { name: "Financial Services", value: 30.0 },
  ],
  [
    { name: "Realty", value: 55.7 },
    { name: "Services", value: 18.8 },
    { name: "Construction ", value: 51.2 },
    { name: "Construction", value: 21.6 },
    { name: "Power", value: 64.9 },
    { name: "Consumer Durables", value: 26.0 },
    { name: "Information Technology", value: 34.1 },
    { name: "Oil, Gas & Consumable fuels", value: 43.9 },
    { name: "Media Entertainment & Publication", value: 17.9 },
    { name: "FMCG", value: 15.6 },
    { name: "Consumer Services", value: 15.9 },
    { name: "Telecommunication", value: 22.7 },
    { name: "Healthcare", value: 19.7 },
    { name: "Textiles", value: 22.2 },
    { name: "Auto", value: 27.2 },
    { name: "Metals & Mining", value: 30.3 },
    { name: "Forest Materials", value: 15.6 },
    { name: "Capital Goods", value: 41.6 },
    { name: "Chemicals", value: 19.9 },
    { name: "Financial Services", value: 30.0 },
  ],
];
